import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">
          <header className="nav">
            <div className="brand">
              <span className="mono">Client workflow</span>
              <span className="dot">.</span>
              <span className="mono">mvp</span>
            </div>

            <nav className="row">
              <a className="kicker" href="/">
                Home
              </a>
              <a className="kicker" href="/login">
                Login
              </a>
              <a className="kicker" href="/dashboard">
                Dashboard
              </a>
            </nav>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
